import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import pandas as pd

__author__ = 'Rasmus Magnusson, Eduard Ghemes'
__COPYRIGHT__ = 'Copyright (C) 2024 Rasmus Magnusson, Eduard Ghemes'
__contact__ = 'rasma774@gmail.com'

_goldenratio = (1 + (5**(.5)))/2

def _corr_ax(ax, float_y: bool = True):
    """
    Customizes the appearance of axes in matplotlib plots.
    
    This function modifies the appearance of the axes passed to it, specifically by hiding 
    the top and right spines (borders). It also sets the linewidth of the remaining spines 
    and adjusts tick parameters.
    
    Parameters:
    ax : matplotlib.axes.Axes
    float_y [Default = True]: If True, the bottom spine is searated from the plot. 
    """
    # Hide the top and right spines for a cleaner look
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    
    # Increase the linewidth of the left and bottom spines for visibility
    ax.spines['left'].set_linewidth(2)
    ax.spines['bottom'].set_linewidth(2)
    
    if float_y:
        ax.spines['bottom'].set_position(('outward', 20))
        
    # Customize the appearance of the ticks
    ax.tick_params(axis='both',
                   width=2,
                   length=4,
                   labelsize=14)

def _get_template(n_subs: int):
    """
    Generates a matplotlib figure and axes with a specified number of subplots arranged vertically.
    
    This function creates a figure and a series of subplots based on the number of subplots 
    requested. It uses the golden ratio to determine the width and height of the plots. 
    Each axis is then customized using the `_corr_ax` function defined above.
    
    Parameters:
    n_subs: The number of subplots to create in the figure.
        
    Returns:
    f: matplotlib.figure.Figure
    ax: matplotlib.axes.Axes
    """
    # Create a figure and subplots
    f, ax = plt.subplots(n_subs,
                         1,
                         figsize=(4**_goldenratio , 8*n_subs))

    # Small trick to not have to conv ax regardless of being itreable or not
    try:
        # Apply customizations to each axis.
        # If ax is iterable (multiple subplots), iterate through each.
        [_corr_ax(tmp, False) for tmp in ax]
        for ax_tmp in ax[1:]:
            ax_tmp.spines['left'].set_visible(True)
            ax_tmp.tick_params(axis='y',
                               which='both',
                               left=True,
                               labelleft=True)
    except TypeError:
        # If ax is not iterable (single subplot), apply customizations directly
        _corr_ax(ax, False)
    return f, ax

def _split_lines(lines: list, textlength: int):
    """
    Splits lines of text into multiple lines if they exceed a certain length.
    
    Parameters:
    lines: The lines of text to potentially split.
    textlength: The maximum allowed length of any line before splitting.
    """
    for i, lbl in enumerate(lines):
        if len(lbl) > textlength:
            # Find indices of whitespace characters
            lbl = list(lbl)
            ws = np.where(np.array(lbl) == ' ')[0]
            # Continue if less than two whitespaces found
            if len(ws) < 2:
                continue
            # If the second last whitespace is beyond the allowed text length,
            # find the first whitespace beyond textlength and insert a newline there.
            if not ws[-2] <= textlength:
                place = ws[np.where(ws > textlength)][0]
                lbl = list(lbl)
                lbl[place] = '\n'
                lbl = ''.join(lbl)
                lines[i] = lbl
    return lines

def plot_enrichments(
    enr: pd.DataFrame,
    savename: str = None,
    plot_Ntop: int = 5,
    textlength: int = 30,
    cmap = mpl.cm.RdYlBu,
    sorton: str = 'OR',
    padding: float = 1,
    ):
    """
    Plots enrichment results with options for sorting, coloring, and text formatting.
    
    Parameters:
    enr: The enrichment dataframe, as generated by NetAn.
    savename [Default = None]: Set a savename for direct saving. 
    plot_Ntop [Default = 5]: The number of top annotations to plot. 
    textlength [Default = 30]: The number of characters before break line for tick labels.
    cmap [Default = mpl.cm.RdYlBu]: LinearSegmentedColormap from matplotlib.cm
    sorton [Default = 'OR']: Set on whether to sort enrichment results on p-values or Odds Ratios (OR).
    padding [Default = 1]: Change the distances between the bars.

    Returns:
    f: matplotlib.pyplot.Figure
    ax: matplotlib.pyplot.Axes
    """
    # Template fetching
    f, ax = _get_template(1)

    # Adjust number of top annotations to plot
    if plot_Ntop is None:
        plot_Ntop = (enr.p_adj <= 0.05).sum()

    # Sort the DataFrame based on the specified criterion
    # Check if all p_adj values are equal
    if len(enr.p_adj.unique()) == 1 and sorton == 'pval':
        # If all p_adj values are equal and user chooses pval, sort based on pval instead
        enr = enr.sort_values('pval', ascending=True)
        print(f'All adjusted p-values are equal, sorting by non-adjusted p-values.')
    else:
        if sorton == 'OR':
            enr = enr.sort_values('OR', ascending=False)
        elif sorton == 'pval':
            enr = enr.sort_values('p_adj', ascending=True)

    # Replace 0 p-values with the smallest observed non-zero p-value
    if np.any(enr.p_adj == 0):
        print('Replacing 0 p-values with smallest observed')
        p_adj_tmp = enr.p_adj.copy()
        smallest_nonzero = p_adj_tmp.unique()[1]
        p_adj_tmp [p_adj_tmp == 0] = smallest_nonzero
        enr['p_adj'] = p_adj_tmp
        
    # Transform p-values for plotting
    p_trans = -np.log10(enr.p_adj.iloc[:plot_Ntop])

    # Setup for the colorbar
    norm = mpl.colors.Normalize(vmin=np.min((p_trans.min(),
                                             -np.log10(0.05))),
                                vmax=p_trans.max())

    # Split long labels if necessary
    if textlength is not None:
        labels = _split_lines(list(enr.index), textlength)

    # Plot bars for the top N enrichments
    for i in range(plot_Ntop):
        ax.barh(padding*(plot_Ntop - i),
                width=enr.OR.iloc[i],
                height=0.7, color=cmap(norm(p_trans.iloc[i])))

    # Set plot limits and labels
    ax.set_xlim([0, enr.OR.iloc[:i].max()*1.2])
    ax.set_yticks(padding*np.array(range(1, 1 + plot_Ntop)))
    ax.set_yticklabels(labels[:plot_Ntop][::-1], fontsize=20)
    ax.set_xlabel('Odds Ratio', fontsize=17)
    
    # Create and format the colorbar
    colorbar = f.colorbar(mpl.cm.ScalarMappable(norm=norm,
                                                cmap=cmap),
                          ax=ax,
                          shrink=0.4,
                          pad = 0.15)
    colorbar.set_label(r'-log$_{10}$ p', fontsize=15, labelpad=-55)

    # Save the figure if a savename is provided
    if  savename is not None:
        f.savefig(savename, bbox_inches='tight')

    return f, ax

def plot_enrichment_clusters(
    enrichments: pd.DataFrame,
    savename: str = None,
    plot_Ntop: int = 5,
    textlength: int = 30,
    cmap = mpl.cm.RdYlBu,
    sorton: str = 'OR',
    padding: float = 1,
    ):
    """Similar to the other plotting function, but this plots clusters.
    """
    
    # Initialize the figure with a subplot for each cluster
    f, ax = _get_template(len(enrichments))

    all_ps = [] # Store all p-values
    all_annots = [] # Store all annotations
    
    # Process each cluster
    for enr_key in enrichments:
        # Assume each key maps to a list with the DataFrame as the first element
        enr_tmp = enrichments[enr_key][0]
        
        # From now on the code is similar to the previous function
        if len(enr_tmp.p_adj.unique()) == 1 and sorton == 'pval':
            # If all p_adj values are equal and user chooses pval, sort based on pval instead
            enr_tmp = enr_tmp.sort_values('pval', ascending=True)
            print(f'{enr_key}: all adjusted p-values are equal, sorting by non-adjusted p-values.')
        else:
            if sorton == 'OR':
                enr_tmp = enr_tmp.sort_values('OR', ascending=False)
            elif sorton == 'pval':
                enr_tmp = enr_tmp.sort_values('p_adj', ascending=True)
        
        all_ps.append(-np.log10(enr_tmp.p_adj.values)[:plot_Ntop])
        labels = list(enr_tmp.index[:plot_Ntop].values[::-1])
        
        if textlength is not None:
            labels = _split_lines(labels, textlength)
            
        all_annots.append([labels,
                           all_ps[-1],
                          enr_tmp.OR.values[:plot_Ntop]])
        
    all_ps = np.concatenate(all_ps) # Flatten the list of p-values for normalization

    if np.any(np.isinf(all_ps)):
        print('Replacing 0 p-values with smallest observed')
        all_ps[np.isinf(all_ps)] = np.unique(all_ps)[-2] # Replace inf with the second smallest value

    norm = mpl.colors.Normalize(vmin=np.min((all_ps.min(),
                                             -np.log10(0.05))),
                                vmax=all_ps.max())

    # Plot each dataset
    for i in range(len(ax)):
        for j in range(plot_Ntop):
            ax[i].barh(padding*(plot_Ntop - j),
                    width=all_annots[i][2][j],
                    height=0.7, color=cmap(norm(all_annots[i][1][j])))

        ax[i].set_yticks(padding*np.array(range(1, 1 + plot_Ntop)))
        ax[i].set_yticklabels(all_annots[i][0], rotation=0, fontsize=20)
        ax[i].set_xlabel('Odds Ratio', fontsize=17)
        
    colorbar = f.colorbar(mpl.cm.ScalarMappable(norm=norm,
                                                cmap=cmap),
                          ax=ax,
                          shrink=0.4,
                          pad = 0.15)
    colorbar.set_label(r'-log$_{10}$ p', fontsize=15, labelpad=-55)
    
    # Save the figure if a savename is provided
    if  savename is not None:
        f.savefig(savename, bbox_inches='tight')

    return f, ax
